/**
 * Renders the canonical docs surface for each component preview page:
 *
 *   - A `<section data-docs="example">` is filled with one rendered example
 *     per `(variant, state)` combination using the `@kosmo/ui` factory.
 *   - A `<section data-docs="usage">` shows the HTML + factory snippets
 *     side-by-side so the markup mirrors the runtime output.
 *   - A `<section data-docs="props">` renders the prop table generated by
 *     `packages/kosmo-ui/scripts/extract-props.ts` (see prop-tables.json).
 *
 * Each preview page declares which component it documents via the
 * `data-component` attribute on the `[data-docs]` root.
 */

import {
  createAppBar,
  createButton,
  createInput,
  createListItem,
  createSearch,
  createSubHeader,
  createTabBar,
  BUTTON_VARIANTS,
  BUTTON_STATES,
  INPUT_VARIANTS,
  INPUT_STATES,
  LIST_ITEM_TONES,
  type ButtonState,
  type ButtonVariant,
  type InputState,
  type InputVariant,
  type ListItemTone,
} from '@kosmo/ui';
import { refreshIcons } from '../icons.ts';
import propTables from '../generated/prop-tables.json' with { type: 'json' };

interface PropDescriptor {
  name: string;
  type: string;
  optional: boolean;
  default?: string;
  description?: string;
}

interface ComponentDescriptor {
  name: string;
  displayName: string;
  props: PropDescriptor[];
}

const PROP_TABLES = propTables as ComponentDescriptor[];

interface ExampleSpec {
  label: string;
  factorySnippet: string;
  htmlSnippet: string;
  build: () => HTMLElement;
}

const EXAMPLES: Record<string, ExampleSpec[]> = {
  button: BUTTON_VARIANTS.flatMap<ExampleSpec>((variant) =>
    BUTTON_STATES.map<ExampleSpec>((state) => ({
      label: `${capitalize(variant)} · ${state}`,
      factorySnippet: `createButton({ label: 'Login', variant: '${variant}', state: '${state}' })`,
      htmlSnippet:
        `<button class="kosmo-btn kosmo-btn--${variant}${stateClass(state)}"` +
        `${state === 'disabled' ? ' disabled' : ''}>\n` +
        `  <span class="kosmo-btn-face">Login</span>\n` +
        `</button>`,
      build: () =>
        createButton({
          label: 'Login',
          variant: variant as ButtonVariant,
          state: state as ButtonState,
        }).el,
    })),
  ),
  input: INPUT_VARIANTS.flatMap<ExampleSpec>((variant) =>
    INPUT_STATES.map<ExampleSpec>((state) => ({
      label: `${capitalize(variant)} · ${state}`,
      factorySnippet: `createInput({ variant: '${variant}', state: '${state}', placeholder: 'you@example.com' })`,
      htmlSnippet:
        `<div class="kosmo-input${variant === 'large' ? ' kosmo-input--large' : ''}${stateClass(state)}">\n` +
        `  <label class="kosmo-input-face">\n` +
        `    <${variant === 'large' ? 'textarea' : 'input'} class="kosmo-input-field"${variant === 'large' ? '' : ' type="email"'} />\n` +
        `  </label>\n</div>`,
      build: () =>
        createInput({
          variant: variant as InputVariant,
          state: state as InputState,
          placeholder: 'you@example.com',
          ariaLabel: 'Email',
          value: state === 'idle' ? '' : 'joe@example.com',
        }).el,
    })),
  ),
  'tab-bar': [
    {
      label: 'Default',
      factorySnippet:
        "createTabBar({ items: [{ id: 'fav', label: 'Favorites' }, { id: 'pl', label: 'Plugins' }, { id: 'tl', label: 'Tools' }, { id: 'st', label: 'Settings' }], activeId: 'pl' })",
      htmlSnippet:
        `<div class="kosmo-tab-bar">\n` +
        `  <button class="kosmo-tab">Favorites</button>\n` +
        `  <button class="kosmo-tab is-active">Plugins</button>\n` +
        `  <button class="kosmo-tab">Tools</button>\n` +
        `  <button class="kosmo-tab">Settings</button>\n` +
        `</div>`,
      build: () =>
        createTabBar({
          items: [
            { id: 'fav', label: 'Favorites' },
            { id: 'pl', label: 'Plugins' },
            { id: 'tl', label: 'Tools' },
            { id: 'st', label: 'Settings' },
          ],
          activeId: 'pl',
          ariaLabel: 'Demo tabs',
        }).el,
    },
    {
      label: 'With disabled tab',
      factorySnippet:
        "createTabBar({ items: [{ id: 'fav', label: 'Favorites' }, { id: 'pl', label: 'Plugins', disabled: true }, { id: 'st', label: 'Settings' }], activeId: 'fav' })",
      htmlSnippet:
        `<div class="kosmo-tab-bar">\n` +
        `  <button class="kosmo-tab is-active">Favorites</button>\n` +
        `  <button class="kosmo-tab is-disabled" disabled>Plugins</button>\n` +
        `  <button class="kosmo-tab">Settings</button>\n` +
        `</div>`,
      build: () =>
        createTabBar({
          items: [
            { id: 'fav', label: 'Favorites' },
            { id: 'pl', label: 'Plugins', disabled: true },
            { id: 'st', label: 'Settings' },
          ],
          activeId: 'fav',
          ariaLabel: 'Demo tabs',
        }).el,
    },
  ],
  'list-item': LIST_ITEM_TONES.flatMap<ExampleSpec>((tone) => [
    {
      label: `${capitalize(tone)} · with action`,
      factorySnippet: `createListItem({ icon: 'layout-grid', label: 'Layout', tone: '${tone}', action: { icon: 'settings-2', ariaLabel: 'Settings' } })`,
      htmlSnippet:
        `<div class="kosmo-list-item${toneClass(tone)}">\n` +
        `  <i data-lucide="layout-grid"></i>\n` +
        `  <span class="kosmo-list-item-label">Layout</span>\n` +
        `  <button class="kosmo-list-item-action"><i data-lucide="settings-2"></i></button>\n` +
        `</div>`,
      build: () =>
        createListItem({
          icon: 'layout-grid',
          label: tone === 'danger' ? 'Sign out' : 'Layout',
          tone: tone as ListItemTone,
          action: { icon: 'settings-2', ariaLabel: 'Settings' },
        }).el,
    },
  ]),
  search: [
    {
      label: 'Default',
      factorySnippet: "createSearch({ placeholder: 'Search' })",
      htmlSnippet:
        `<form class="kosmo-search" role="search">\n` +
        `  <input class="kosmo-search-field" type="search" placeholder="Search" />\n` +
        `  <span class="kosmo-search-icon"><i data-lucide="search"></i></span>\n` +
        `  <button class="kosmo-search-clear" type="button"><i data-lucide="x"></i></button>\n` +
        `</form>`,
      build: () => withCanvas(createSearch({ placeholder: 'Search' }).el),
    },
    {
      label: 'With value',
      factorySnippet: "createSearch({ placeholder: 'Search', value: 'Layout' })",
      htmlSnippet:
        `<form class="kosmo-search has-text" role="search">\n` +
        `  <input class="kosmo-search-field" type="search" value="Layout" />\n` +
        `  ...\n` +
        `</form>`,
      build: () => withCanvas(createSearch({ placeholder: 'Search', value: 'Layout' }).el),
    },
  ],
  'sub-header': [
    {
      label: 'Default',
      factorySnippet: "createSubHeader({ label: 'COPY DESIGN STYLES' })",
      htmlSnippet: `<h3 class="kosmo-sub-header">COPY DESIGN STYLES</h3>`,
      build: () => createSubHeader({ label: 'COPY DESIGN STYLES' }).el,
    },
    {
      label: 'Decorative',
      factorySnippet: "createSubHeader({ label: 'INTERNAL', as: 'div' })",
      htmlSnippet: `<div class="kosmo-sub-header">INTERNAL</div>`,
      build: () => createSubHeader({ label: 'INTERNAL', as: 'div' }).el,
    },
  ],
  'app-bar': [
    {
      label: 'Plugin actions · favourite + delete',
      factorySnippet:
        "createAppBar({\n" +
        "  ariaLabel: 'Plugin actions',\n" +
        "  leading: { icon: 'chevron-left', ariaLabel: 'Back' },\n" +
        "  title: 'v1.0',\n" +
        "  trailing: [\n" +
        "    { icon: 'star', ariaLabel: 'Remove from favourites', tone: 'favourite' },\n" +
        "    { icon: 'trash-2', ariaLabel: 'Delete plugin' },\n" +
        "  ],\n" +
        "})",
      htmlSnippet:
        `<div class="kosmo-app-bar" role="toolbar" aria-label="Plugin actions">\n` +
        `  <button class="kosmo-app-bar__icon-btn kosmo-app-bar__icon-btn--default" aria-label="Back">\n` +
        `    <i data-lucide="chevron-left"></i>\n` +
        `  </button>\n` +
        `  <span class="kosmo-app-bar__title">v1.0</span>\n` +
        `  <button class="kosmo-app-bar__icon-btn kosmo-app-bar__icon-btn--favourite" aria-label="Remove from favourites">\n` +
        `    <i data-lucide="star"></i>\n` +
        `  </button>\n` +
        `  <button class="kosmo-app-bar__icon-btn kosmo-app-bar__icon-btn--default" aria-label="Delete plugin">\n` +
        `    <i data-lucide="trash-2"></i>\n` +
        `  </button>\n` +
        `</div>`,
      build: () =>
        withCanvas(
          createAppBar({
            ariaLabel: 'Plugin actions',
            leading: { icon: 'chevron-left', ariaLabel: 'Back' },
            title: 'v1.0',
            trailing: [
              { icon: 'star', ariaLabel: 'Remove from favourites', tone: 'favourite' },
              { icon: 'trash-2', ariaLabel: 'Delete plugin' },
            ],
          }).el,
        ),
    },
    {
      label: 'Title only',
      factorySnippet: "createAppBar({ ariaLabel: 'Plugin actions', title: 'Settings' })",
      htmlSnippet:
        `<div class="kosmo-app-bar" role="toolbar" aria-label="Plugin actions">\n` +
        `  <span class="kosmo-app-bar__title">Settings</span>\n` +
        `</div>`,
      build: () =>
        withCanvas(createAppBar({ ariaLabel: 'Plugin actions', title: 'Settings' }).el),
    },
  ],
};

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function stateClass(state: string): string {
  if (state === 'idle') return '';
  return ` is-${state}`;
}

function toneClass(tone: string): string {
  if (tone === 'default') return '';
  return ` kosmo-list-item--${tone}`;
}

function withCanvas(el: HTMLElement): HTMLElement {
  el.classList.add('component-preview-canvas');
  el.classList.add('component-preview-canvas--rounded');
  return el;
}

function renderExamples(component: string, root: HTMLElement): void {
  const examples = EXAMPLES[component];
  if (!examples) return;
  root.textContent = '';
  for (const example of examples) {
    const section = document.createElement('div');
    section.className = 'component-preview-section';
    const label = document.createElement('span');
    label.className = 'component-preview-label';
    label.textContent = example.label;
    section.appendChild(label);
    section.appendChild(example.build());
    root.appendChild(section);
  }
}

function renderUsage(component: string, root: HTMLElement): void {
  const examples = EXAMPLES[component];
  if (!examples || examples.length === 0) return;
  const first = examples[0];
  if (!first) return;
  root.textContent = '';

  const factoryHeader = document.createElement('div');
  factoryHeader.className = 'component-preview-label';
  factoryHeader.textContent = 'TypeScript';
  const factoryBlock = document.createElement('pre');
  factoryBlock.className = 'component-docs-code';
  factoryBlock.textContent = `import { create${displayNameFor(component)} } from '@kosmo/ui';\n\nconst instance = ${first.factorySnippet};\ndocument.body.appendChild(instance.el);`;

  const htmlHeader = document.createElement('div');
  htmlHeader.className = 'component-preview-label';
  htmlHeader.textContent = 'HTML';
  const htmlBlock = document.createElement('pre');
  htmlBlock.className = 'component-docs-code';
  htmlBlock.textContent = first.htmlSnippet;

  root.append(factoryHeader, factoryBlock, htmlHeader, htmlBlock);
}

function displayNameFor(component: string): string {
  return PROP_TABLES.find((c) => c.name === component)?.displayName ?? capitalize(component);
}

function renderProps(component: string, root: HTMLElement): void {
  const descriptor = PROP_TABLES.find((c) => c.name === component);
  if (!descriptor) return;
  root.textContent = '';

  const table = document.createElement('table');
  table.className = 'component-docs-props';
  const thead = document.createElement('thead');
  thead.innerHTML =
    '<tr>' +
    '<th scope="col">Prop</th>' +
    '<th scope="col">Type</th>' +
    '<th scope="col">Required</th>' +
    '<th scope="col">Description</th>' +
    '</tr>';
  table.appendChild(thead);

  const tbody = document.createElement('tbody');
  for (const prop of descriptor.props) {
    const tr = document.createElement('tr');

    const name = document.createElement('td');
    const code = document.createElement('code');
    code.textContent = prop.name;
    name.appendChild(code);
    tr.appendChild(name);

    const type = document.createElement('td');
    const typeCode = document.createElement('code');
    typeCode.textContent = prop.type;
    type.appendChild(typeCode);
    tr.appendChild(type);

    const required = document.createElement('td');
    required.textContent = prop.optional ? 'Optional' : 'Required';
    tr.appendChild(required);

    const description = document.createElement('td');
    description.textContent = prop.description ?? '—';
    tr.appendChild(description);

    tbody.appendChild(tr);
  }
  table.appendChild(tbody);
  root.appendChild(table);
}

export function initComponentDocs(): void {
  const docsRoot = document.querySelector<HTMLElement>('[data-docs-root]');
  if (!docsRoot) return;
  const component = docsRoot.dataset.component;
  if (!component) return;

  const examplesEl = docsRoot.querySelector<HTMLElement>('[data-docs="examples"]');
  const usageEl = docsRoot.querySelector<HTMLElement>('[data-docs="usage"]');
  const propsEl = docsRoot.querySelector<HTMLElement>('[data-docs="props"]');

  if (examplesEl) renderExamples(component, examplesEl);
  if (usageEl) renderUsage(component, usageEl);
  if (propsEl) renderProps(component, propsEl);

  refreshIcons();
}
